In [ ]:
Q1. What are the benefits of the built-in array package, if any?

In [ ]:
An array is a collection of items stored at contiguous memory locations. The idea is to store multiple 
items of the same type together. This makes it easier to calculate the position of each element by simply 
adding an offset to a base value, i.e., the memory location of the first element of the array (generally 
denoted by the name of the array).They can be useful when we have to manipulate only a specific data 
type values.An array can hold many values under a single name, and you can access the values by 
referring to an index number. If you need to allocate an array that you know will not change, then arrays
can be faster and use less memory than lists.Faster calculations and analysis than lists

In [ ]:
Q2. What are some of the array package's limitations?

In [ ]:
All elements of the array must be of the same type.Array are not as flexible as lists with respect to
data type.Array package is less efficient and executed with more code as compared to numpy array package.
Does not support advanced scientific/mathematical Python-based software as compared to numpy array.

In [ ]:
Q3. Describe the main differences between the array and numpy packages.

In [ ]:
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the
size of an ndarray will create a new array and delete the original.The elements in a NumPy array are all 
required to be of the same data type, and thus will be the same size in memory. The exception: one can have
arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. 
Typically, such operations are executed more efficiently and with less code than is possible using 
Python’s built-in sequences.A growing plethora of scientific and mathematical Python-based packages are
using NumPy arrays; though these typically support Python-sequence input, they convert such input to 
NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to 
efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just 
knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use 
NumPy arrays.
Numpy arrays are static python arrays are dynamic.

In [30]:
import array as arr
a=arr.array('i',[1,2,3,4])
b=np.array([1,2,3,4])
print(type(a),type(b))


<class 'array.array'> <class 'numpy.ndarray'>


In [ ]:
Q4. Explain the distinctions between the empty, ones, and zeros functions.

In [ ]:
numpy.empty(shape, dtype=float, order='C', *, like=None)
Return a new array of given shape and type, without initializing entries.

numpy.ones(shape, dtype=None, order='C', *, like=None)[source]
Return a new array of given shape and type, filled with ones.

numpy.zeros(shape, dtype=float, order='C', *, like=None)
Return a new array of given shape and type, filled with zeros.

In [4]:
import numpy as np
a=np.empty((2,5))
b=np.ones((2,5))
c=np.zeros((2,5))
a,b,c

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [ ]:
Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable
argument?

In [ ]:
numpy.fromfunction(function, shape, **kwargs)
function	function construct an array by executing a function over each coordinate and the resulting 
array, therefore, has a value fn(x, y, z) at coordinate (x, y, z). For example, if shape were (2, 2), 
then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])

shape	Shape of the output array, which also determines the shape of the coordinate arrays passed to 
function.

In [15]:
gfg = np.fromfunction(lambda i, j: i +j, (2, 2), dtype = int)
print(gfg)

[[0 1]
 [1 2]]


In [ ]:
Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

In [16]:
a=np.array([1,6,45,96,78])

In [19]:
print(a+1)

[ 2  7 46 97 79]


In [ ]:
As can been in above expression the given operation with single operand is performed on every element
within that nd array.

In [ ]:
Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

In [23]:
a=np.array([1,6,45,96,78])
copy_a=np.array([1,6,45,96,78])
a*=2
copy_a+=1
a,copy_a

(array([  2,  12,  90, 192, 156]), array([ 2,  7, 46, 97, 79]))

In [ ]:
As we can see in above combined operation-assign operators work on every single element within numpy array

In [ ]:
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
one of these arrays?

In [ ]:
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the
size of an ndarray will create a new array and delete the original.

In [ ]:
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

In [35]:
a=np.array([1,2,3,4])
b=np.array([5,4,3,2])
c=np.array([1,2])
print(a*b,a+b)
print(a*c)

[5 8 9 8] [6 6 6 6]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
As we can see when two numpy have array same size given operation like + or * is performed with respect to
corresponding elements,when there is no matching in array sizes size it gives error.

In [ ]:
Q10. What is the best way to use a Boolean array to mask another array?

In [48]:
a=np.fromfunction(lambda c,y:c+y,(1,8),dtype=int)
print(a)
print(a%2==0)
print(a[a%2==0])

[[0 1 2 3 4 5 6 7]]
[[ True False  True False  True False  True False]]
[0 2 4 6]


In [ ]:
As we see we can use this code to mask another array by putting condition such that whatever give true value
will be returned back.

In [ ]:
Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

In [64]:
f=[]
def userstd(a):
    
    x=len(a)
    y=sum(a)/x
    f=[(p-y)**2 for p in a]
    
    h=(sum(f)/x)**0.5
    return h

In [68]:
import statistics
import time
a=[1,2,3,4,5,6,7,8,9,10,11]
begin1=time.time()
b=statistics.pstdev(a)
time.sleep(1)
end1=time.time()
begin2=time.time()
c=np.std(a)
time.sleep(1)
end2=time.time()
begin3=time.time()
d=userstd(a) 
time.sleep(1)
end3=time.time()
b,(end1-begin1),c,(end2-begin2),d,(end3-begin3)

(3.1622776601683795,
 1.0019965171813965,
 3.1622776601683795,
 1.0115983486175537,
 3.1622776601683795,
 1.0100221633911133)

In [ ]:
Hence first command gives results in fastest time hence numpy array calculations are fastest.
1)b=statistics.pstdev(a)
2)d=userstd(a) 
3)c=np.std(a)

In [ ]:
12. What is the dimensionality of a Boolean mask-generated array?

In [73]:
a=np.fromfunction(lambda c,y:c+y,(4,8),dtype=int)
print(a)
print(a%2==0)
print(a[a%2==0],'shape is',a[a%2==0].shape)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]]
[[ True False  True False  True False  True False]
 [False  True False  True False  True False  True]
 [ True False  True False  True False  True False]
 [False  True False  True False  True False  True]]
[ 0  2  4  6  2  4  6  8  2  4  6  8  4  6  8 10] shape is (16,)


In [ ]:
Hence it returns array with single row and number of columns are equal to number of elements present in
the returned array.